=== hmrc/self-employment-business-api/resources/public/api/conf/2.0/schemas/retrieve_period_summary_response_with_negatives.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Self-Employment Period Summary",
  "description": "Retrieves a self-employment period summary.",
  "type": "object",
  "properties": {
    "periodDates": {
      "$ref": "periodSummary/period_dates.json"
    },
    "periodIncome": {
      "$ref": "periodSummary/period_income.json"
    },
    "periodExpenses": {
      "$ref": "periodSummary/period_expenses_with_negatives.json"
    },
    "periodDisallowableExpenses": {
      "$ref": "periodSummary/period_disallowable_expenses_with_negatives.json"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource.",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint.",
            "type": "string",
            "example": "/individuals/business/self-employment/{nino}/{businessId}/period/{periodId}"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource.",
            "type": "string",
            "enum": [
              "self",
              "amend-self-employment-period-summary",
              "list-self-employment-period-summaries"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint.",
            "type": "string",
            "enum": [
              "GET",
              "PUT"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "periodDates"
  ],
  "additionalProperties": false
}

=== hmrc/self-employment-business-api/resources/public/api/conf/5.0/examples/retrievePeriodSummary/def2/non_consolidated_response.json
{
  "periodDates": {
    "periodStartDate": "2019-04-06",
    "periodEndDate": "2019-07-05"
  },
  "periodIncome": {
    "turnover": 200.00,
    "other": 200.00,
    "taxTakenOffTradingIncome": 1000.99
  },
  "periodExpenses": {
    "costOfGoods": 200.00,
    "paymentsToSubcontractors": -200.00,
    "wagesAndStaffCosts": -200.00,
    "carVanTravelExpenses": -200.00,
    "premisesRunningCosts": 200.00,
    "maintenanceCosts": 200.00,
    "adminCosts": -200.00,
    "businessEntertainmentCosts": -200.00,
    "advertisingCosts": -200.00,
    "interestOnBankOtherLoans": 200.00,
    "financeCharges": 200.00,
    "irrecoverableDebts": 200.00,
    "professionalFees": 200.00,
    "depreciation": 200.00,
    "otherExpenses": -200.00
  },
  "periodDisallowableExpenses": {
    "costOfGoodsDisallowable": 200.00,
    "paymentsToSubcontractorsDisallowable": -200.00,
    "wagesAndStaffCostsDisallowable": -200.00,
    "carVanTravelExpensesDisallowable": -200.00,
    "premisesRunningCostsDisallowable": 200.00,
    "maintenanceCostsDisallowable": 200.00,
    "adminCostsDisallowable": -200.00,
    "businessEntertainmentCostsDisallowable": -200.00,
    "advertisingCostsDisallowable": -200.00,
    "interestOnBankOtherLoansDisallowable": 200.00,
    "financeChargesDisallowable": 200.00,
    "irrecoverableDebtsDisallowable": 200.00,
    "professionalFeesDisallowable": 200.00,
    "depreciationDisallowable": 200.00,
    "otherExpensesDisallowable": -200.00
  },
  "links": [
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period/2019-06-12_2020-06-12",
      "rel": "amend-self-employment-period-summary",
      "method": "PUT"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period/2019-06-12_2020-06-12",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period",
      "rel": "list-self-employment-period-summaries",
      "method": "GET"
    }
  ]
}

=== hmrc/self-employment-business-api/resources/public/api/conf/5.0/examples/retrievePeriodSummary/def2/consolidated_response.json
{
  "periodDates": {
    "periodStartDate": "2019-07-06",
    "periodEndDate": "2019-10-05"
  },
  "periodIncome": {
    "turnover": 200.00,
    "other": 200.00,
    "taxTakenOffTradingIncome": 1000.99
  },
  "periodExpenses": {
    "consolidatedExpenses": -200.00
  },
  "links": [
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period/2019-06-12_2020-06-12",
      "rel": "amend-self-employment-period-summary",
      "method": "PUT"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period/2019-06-12_2020-06-12",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period",
      "rel": "list-self-employment-period-summaries",
      "method": "GET"
    }
  ]
}
