=== hmrc/self-employment-business-api/resources/public/api/conf/3.0/schemas/pre_TYS/create_period_summary_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Before TY 2023-24",
  "description": "Create a Self-Employment Period Summary Request",
  "type": "object",
  "properties": {
    "periodDates": {
      "$ref": "../periodSummary/period_dates.json"
    },
    "periodIncome": {
      "$ref": "../periodSummary/pre_TYS/period_income.json"
    },
    "periodExpenses": {
      "$ref": "../periodSummary/pre_TYS/period_expenses.json"
    },
    "periodDisallowableExpenses": {
      "$ref": "../periodSummary/pre_TYS/period_disallowable_expenses.json"
    }
  },
  "additionalProperties": false,
  "required": [
    "periodDates"
  ]
}

=== hmrc/self-employment-business-api/resources/public/api/conf/3.0/examples/createPeriodSummary/def1/non_consolidated_request.json
{
  "periodDates": {
    "periodStartDate": "2019-04-06",
    "periodEndDate": "2019-07-05"
  },
  "periodIncome": {
    "turnover": 1000.99,
    "other": 1000.09
  },
  "periodExpenses": {
    "costOfGoods": 1000.99,
    "paymentsToSubcontractors": 1000.99,
    "wagesAndStaffCosts": 1000.99,
    "carVanTravelExpenses": 1000.99,
    "premisesRunningCosts": -99999.99,
    "maintenanceCosts": -1000.99,
    "adminCosts": 1000.99,
    "businessEntertainmentCosts": 1000.99,
    "advertisingCosts": 1000.99,
    "interestOnBankOtherLoans": -1000.99,
    "financeCharges": -1000.99,
    "irrecoverableDebts": -1000.99,
    "professionalFees": -99999999999.99,
    "depreciation": -1000.99,
    "otherExpenses": 1000.99
  },
  "periodDisallowableExpenses": {
    "costOfGoodsDisallowable": 91000.99,
    "paymentsToSubcontractorsDisallowable": 1000.99,
    "wagesAndStaffCostsDisallowable": 1000.99,
    "carVanTravelExpensesDisallowable": 1000.99,
    "premisesRunningCostsDisallowable": -1000.99,
    "maintenanceCostsDisallowable": -999.99,
    "adminCostsDisallowable": 1000.99,
    "businessEntertainmentCostsDisallowable": 1000.99,
    "advertisingCostsDisallowable": 1000.99,
    "interestOnBankOtherLoansDisallowable": -1000.99,
    "financeChargesDisallowable": -9999.99,
    "irrecoverableDebtsDisallowable": 1000.99,
    "professionalFeesDisallowable": 1000.99,
    "depreciationDisallowable": -99999999999.99,
    "otherExpensesDisallowable": 1000.99
  }
}
