=== hmrc/self-employment-business-api/resources/public/api/conf/1.0/schemas/create_periodic_summary_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Create a Self-Employment Period Summary",
  "description": "Create a Self-Employment Period Summary Request",
  "type": "object",
  "properties": {
    "periodDates": {
      "$ref": "periodic/period_dates.json"
    },
    "periodIncome": {
      "$ref": "periodic/period_income.json"
    },
    "periodAllowableExpenses": {
      "$ref": "periodic/period_allowable_expenses.json"
    },
    "periodDisallowableExpenses": {
      "$ref": "periodic/period_disallowable_expenses.json"
    }
  },
  "additionalProperties": false,
  "required": [
    "periodDates"
  ]
}

=== hmrc/self-employment-business-api/resources/public/api/conf/1.0/examples/create_period_summary_request.json
{
  "periodDates": {
    "periodStartDate": "2019-07-06",
    "periodEndDate": "2019-10-05"
  },
  "periodIncome": {
    "turnover": 1000.99,
    "other": 1000.09
  },
  "periodAllowableExpenses": {
    "costOfGoodsAllowable": 1000.99,
    "paymentsToSubcontractorsAllowable": 1000.99,
    "wagesAndStaffCostsAllowable": 1000.99,
    "carVanTravelExpensesAllowable": 1000.99,
    "premisesRunningCostsAllowable": -99999.99,
    "maintenanceCostsAllowable": -1000.99,
    "adminCostsAllowable": 1000.99,
    "businessEntertainmentCostsAllowable": 1000.99,
    "advertisingCostsAllowable": 1000.99,
    "interestOnBankOtherLoansAllowable": -1000.99,
    "financeChargesAllowable": -1000.99,
    "irrecoverableDebtsAllowable": -1000.99,
    "professionalFeesAllowable": -99999999999.99,
    "depreciationAllowable": -1000.99,
    "otherExpensesAllowable": 1000.99
  },
  "periodDisallowableExpenses": {
    "costOfGoodsDisallowable": 91000.99,
    "paymentsToSubcontractorsDisallowable": 1000.99,
    "wagesAndStaffCostsDisallowable": 1000.99,
    "carVanTravelExpensesDisallowable": 1000.99,
    "premisesRunningCostsDisallowable": -1000.99,
    "maintenanceCostsDisallowable": -999.99,
    "adminCostsDisallowable": 1000.99,
    "businessEntertainmentCostsDisallowable": 1000.99,
    "advertisingCostsDisallowable": 1000.99,
    "interestOnBankOtherLoansDisallowable": -1000.99,
    "financeChargesDisallowable": -9999.99,
    "irrecoverableDebtsDisallowable": 1000.99,
    "professionalFeesDisallowable": 1000.99,
    "depreciationDisallowable": -99999999999.99,
    "otherExpensesDisallowable": 1000.99
  }
}
