=== hmrc/self-employment-business-api/resources/public/api/conf/1.0/schemas/retrieve_annual_summary_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Self Employment Annual Summary",
  "description": "Retrieves a self-employment annual summary for a tax year.",
  "type": "object",
  "properties": {
    "adjustments": {
      "type": "object",
      "properties": {
        "includedNonTaxableProfits": {
          "description": "Income, receipts and other profits included in business income or expenses but not taxable as business profits. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "basisAdjustment": {
          "description": "If your basis period is not the same as your accounting period, enter the adjustment needed to arrive at the profit or loss for the basis period – if the adjustment needs to be taken off the profit figure, this should be negative. Between -99999999999.99 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "overlapReliefUsed": {
          "description": "Overlap relief used this year. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "accountingAdjustment": {
          "description": "Adjustment for change of accounting practice. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "averagingAdjustment": {
          "description": "Averaging adjustment (only for farmers, market gardeners and creators of literary or artistic works) – if the adjustment needs to be taken off the profit figure, this should be negative. Between -99999999999.99 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "lossBroughtForward": {
          "description": "Loss brought forward from earlier years. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "outstandingBusinessIncome": {
          "description": "Any other business income not included in other fields. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "balancingChargeBPRA": {
          "description": "Balancing charge on sale or cessation of business use (only where Business Premises Renovation Allowance has been claimed). Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "balancingChargeOther": {
          "description": "Balancing charge on sale or cessation of business use (where you have disposed of assets for more than their tax value). Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "goodsAndServicesOwnUse": {
          "description": "Value of the normal sale price of goods or stock have been taken out of the business. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        }
      },
      "additionalProperties": false
    },
    "allowances": {
      "type": "object",
      "properties": {
        "annualInvestmentAllowance": {
          "description": "Annual investment allowance on items that qualify up to the AIA amount. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "businessPremisesRenovationAllowance": {
          "description": "Business Premises Renovation Allowance if converting or renovating unused qualifying business premises. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "capitalAllowanceMainPool": {
          "description": "Capital allowances at 18% on equipment, including cars with lower CO2 emissions. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "capitalAllowanceSpecialRatePool": {
          "description": "Capital allowances at 8% on equipment, including cars with higher CO2 emissions. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "zeroEmissionGoodsVehicleAllowance": {
          "description": "Zero emission goods vehicle allowance for goods vehicles purchased for business use. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "enhancedCapitalAllowance": {
          "description": "100% and other enhanced capital allowances. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "allowanceOnSales": {
          "description": "Allowances on sale or cessation of business use (where you have disposed of assets for less than their tax value). Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "capitalAllowanceSingleAssetPool": {
          "description": "Capital Allowances for single asset pool costs. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "tradingAllowance": {
          "description": "A tax exemption of a limited amount for individuals with trading income. Between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "structureAndBuildingAllowance": {
          "description": "Relief on eligible construction costs of non-residential structures and buildings. The value must be between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        },
        "electricChargePointAllowance": {
          "description": "Expenditure incurred on electric charge-point equipment. The value must be between 0 and 99999999999.99.",
          "type": "number",
          "example": "2000.99"
        }
      },
      "additionalProperties": false
    },
    "nonFinancials": {
      "type": "object",
      "properties": {
        "class4NicInfo": {
          "description": "Self-employed profits above a set threshold are subject to Class 4 National Insurance charges.",
          "type": "object",
          "properties": {
            "exemptionCode": {
              "description": "Class 4 exemption codes - becomes mandatory if isExempt flag is set to true. Limited to the following possible values:\n\n001 - Non Resident\n002 - Trustee\n003 - Diver\n004 - Employed earner taxed under ITTOIA 2005\n005 - Over state pension age\n006 - Under 16",
              "type": "string",
              "example": "001 - Non Resident"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource.",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint.",
            "type": "string",
            "example": "/individuals/business/self-employment/{nino}/{businessId}/annual/{taxYear}"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource.",
            "type": "string",
            "enum": [
              "self",
              "create-and-amend-self-employment-annual-summary",
              "delete-self-employment-annual-summary"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint.",
            "type": "string",
            "enum": [
              "GET",
              "PUT",
              "DELETE"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== hmrc/self-employment-business-api/resources/public/api/conf/1.0/examples/retrieve_annual_summary_response.json
{
  "adjustments": {
    "includedNonTaxableProfits": 3123.15,
    "basisAdjustment": 192.25,
    "overlapReliefUsed": 399.00,
    "accountingAdjustment": 31.25,
    "averagingAdjustment": 3134.20,
    "lossBroughtForward": 10.89,
    "outstandingBusinessIncome": 102.10,
    "balancingChargeBPRA": 40.30,
    "balancingChargeOther": 3992.00,
    "goodsAndServicesOwnUse": 391.25
  },
  "allowances": {
    "annualInvestmentAllowance": 3992.10,
    "capitalAllowanceMainPool": 20.11,
    "capitalAllowanceSpecialRatePool": 29.00,
    "zeroEmissionGoodsVehicleAllowance": 500.00,
    "businessPremisesRenovationAllowance": 31.00,
    "enhancedCapitalAllowance": 49.19,
    "allowanceOnSales": 39.48,
    "capitalAllowanceSingleAssetPool": 32.39,
    "tradingAllowance": 85.39,
    "electricChargePointAllowance": 10.79
  },
  "nonFinancials": {
    "class4NicInfo": {
      "exemptionCode": "002 - Trustee"
    }
  },
  "links": [
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/annual/2019-20",
      "rel": "create-and-amend-self-employment-annual-summary",
      "method": "PUT"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/annual/2019-20",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/annual/2019-20",
      "rel": "delete-self-employment-annual-summary",
      "method": "DELETE"
    }
  ]
}
