=== hmrc/self-employment-business-api/resources/public/api/conf/1.0/schemas/retrieve_annual_submission_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Self Employment Annual Summary",
  "description": "Retrieves a self-employment annual summary for a tax year.",
  "type": "object",
  "properties": {
    "adjustments": {
      "type": "object",
      "description": "Object containing the details about annual adjustments",
      "properties": {
        "includedNonTaxableProfits": {
          "description": "Income, receipts and other profits included in business income or expenses but not taxable as business profits. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "basisAdjustment": {
          "description": "If your basis period is not the same as your accounting period, enter the adjustment needed to arrive at the profit or loss for the basis period. If the adjustment needs to be taken off the profit figure, this should be negative. Between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "overlapReliefUsed": {
          "description": "Overlap relief used this year. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "accountingAdjustment": {
          "description": "Adjustment for change of accounting practice. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "averagingAdjustment": {
          "description": "Averaging adjustment (only for farmers, market gardeners and creators of literary or artistic works) – if the adjustment needs to be taken off the profit figure, this should be negative. This value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "outstandingBusinessIncome": {
          "description": "Any other business income not included in other fields. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "balancingChargeBpra": {
          "description": "Balancing charge on sale or cessation of business use (only where Business Premises Renovation Allowance has been claimed). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "balancingChargeOther": {
          "description": "Balancing charge on sale or cessation of business use (where you have disposed of assets for more than their tax value). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "goodsAndServicesOwnUse": {
          "description": "Value of the normal sale price of goods or stock have been taken out of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        }
      },
      "additionalProperties": false
    },
    "allowances": {
      "type": "object",
      "description": "Object containing the details about annual allowances",
      "properties": {
        "annualInvestmentAllowance": {
          "description": "Annual investment allowance on items that qualify up to the AIA amount. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "capitalAllowanceMainPool": {
          "description": "Capital allowances at 18% on equipment, including cars with lower CO2 emissions. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "capitalAllowanceSpecialRatePool": {
          "description": "Capital allowances at 8% on equipment, including cars with higher CO2 emissions. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "zeroEmissionsGoodsVehicleAllowance": {
          "description": "Zero emissions goods vehicle allowance for goods vehicles purchased for business use.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "businessPremisesRenovationAllowance": {
          "description": "Business Premises Renovation Allowance if converting or renovating unused qualifying business premises. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "enhancedCapitalAllowance": {
          "description": "Other enhanced capital allowances.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "allowanceOnSales": {
          "description": "Allowances on sale or cessation of business use (where you have disposed of assets for less than their tax value). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "capitalAllowanceSingleAssetPool": {
          "description": "Claim to capital allowances in respect of all single asset pools. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "electricChargePointAllowance": {
          "description": "The expenditure incurred on electric charge-point equipment. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "zeroEmissionsCarAllowance": {
          "description": "The amount of zero emissions car allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "tradingIncomeAllowance": {
          "description": "The amount of trading allowance (can not be supplied with any other allowances). The value must be between 0 and 1000.00 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        },
        "structuredBuildingAllowance": {
          "type": "array",
          "description": "Details about structured building allowance",
          "items": {
            "type": "object",
            "properties": {
              "amount": {
                "description": "The amount of structured building allowance.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
                "type": "number",
                "example": "2000.99"
              },
              "firstYear": {
                "type": "object",
                "description": "Object containing the details about structured building allowance",
                "properties": {
                  "qualifyingDate": {
                    "description": "The date qualified for structured building allowance. Must conform to the format YYYY-MM-DD.",
                    "type": "string",
                    "example": "2020-01-01"
                  },
                  "qualifyingAmountExpenditure": {
                    "description": "The amount of qualifying expenditure. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                    "type": "number",
                    "example": "2000.99"
                  }
                },
                "required": [
                  "qualifyingDate",
                  "qualifyingAmountExpenditure"
                ]
              },
              "building": {
                "type": "object",
                "description": "Postcode is mandatory and minimum one of name and number field must be supplied",
                "properties": {
                  "name": {
                    "description": "The name of the building.",
                    "type": "string",
                    "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                    "example": "Green Oak’s"
                  },
                  "number": {
                    "description": "The number of the building.",
                    "type": "string",
                    "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                    "example": "16D"
                  },
                  "postcode": {
                    "description": "The postcode for the building.",
                    "type": "string",
                    "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                    "example": "SW1A 2AA"
                  }
                },
                "required": [
                  "postcode"
                ]
              }
            },
            "required": [
              "amount",
              "building"
            ]
          }
        },
        "enhancedStructuredBuildingAllowance": {
          "type": "array",
          "description": "Details about enhanced structured building allowance",
          "items": {
            "type": "object",
            "properties": {
              "amount": {
                "description": "The amount of enhanced structured building allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                "type": "number",
                "example": "5000.99"
              },
              "firstYear": {
                "type": "object",
                "description": "Object containing the details about enhanced structured building allowance",
                "properties": {
                  "qualifyingDate": {
                    "description": "The date qualified for enhanced structured building allowance. Must conform to the format YYYY-MM-DD.",
                    "type": "string",
                    "example": "2020-01-01"
                  },
                  "qualifyingAmountExpenditure": {
                    "description": "The amount of qualifying expenditure. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                    "type": "number",
                    "example": "5000.99"
                  }
                },
                "required": [
                  "qualifyingDate",
                  "qualifyingAmountExpenditure"
                ]
              },
              "building": {
                "type": "object",
                "description": "Object holding enhanced structured building details. Postcode is mandatory and minimum one of name and number field must be supplied",
                "properties": {
                  "name": {
                    "description": "The name of the building.",
                    "type": "string",
                    "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                    "example": "Green Oak’s"
                  },
                  "number": {
                    "description": "The number of the building.",
                    "type": "string",
                    "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                    "example": "16D"
                  },
                  "postcode": {
                    "description": "The postcode for the building.",
                    "type": "string",
                    "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                    "example": "SW1A 2AA"
                  }
                },
                "required": [
                  "postcode"
                ]
              }
            },
            "required": [
              "amount",
              "building"
            ]
          }
        }
      }
    },
    "nonFinancials": {
      "type": "object",
      "description": "Object containing details about annual non financials",
      "properties": {
        "businessDetailsChangedRecently": {
          "description": "A boolean to identify if business details have recently changed. The value must be true or false.",
          "type": "boolean",
          "example": "false"
        },
        "class4NicsExemptionReason": {
          "description": "If exempt from paying Class 4 National Insurance, the reason for exemption.",
          "type": "string",
          "enum": [
            "non-resident",
            "trustee",
            "diver",
            "ITTOIA-2005",
            "over-state-pension-age",
            "under-16"
          ],
          "example": "non-resident"
        }
      },
      "required": [
        "businessDetailsChangedRecently"
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource.",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint.",
            "type": "string",
            "example": "/individuals/business/self-employment/AA999999A/XAIS12345678910/annual/2022-23"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource.",
            "type": "string",
            "enum": [
              "self",
              "create-and-amend-self-employment-annual-submission",
              "delete-self-employment-annual-submission"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint.",
            "type": "string",
            "enum": [
              "GET",
              "PUT",
              "DELETE"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== hmrc/self-employment-business-api/resources/public/api/conf/4.0/examples/retrieveAnnualSubmission/def1/full_response.json
{
  "adjustments": {
    "includedNonTaxableProfits": 210,
    "basisAdjustment": 178.23,
    "overlapReliefUsed": 123.78,
    "accountingAdjustment": 678.9,
    "averagingAdjustment": 674.98,
    "outstandingBusinessIncome": 342.67,
    "balancingChargeBpra": 145.98,
    "balancingChargeOther": 457.23,
    "goodsAndServicesOwnUse": 432.9
  },
  "allowances": {
    "annualInvestmentAllowance": 564.76,
    "capitalAllowanceMainPool": 456.98,
    "capitalAllowanceSpecialRatePool": 352.87,
    "zeroEmissionsGoodsVehicleAllowance": 653.9,
    "businessPremisesRenovationAllowance": 452.98,
    "enhancedCapitalAllowance": 563.23,
    "allowanceOnSales": 678.9,
    "capitalAllowanceSingleAssetPool": 563.89,
    "electricChargePointAllowance": 0,
    "structuredBuildingAllowance": [
      {
        "amount": 564.89,
        "firstYear": {
          "qualifyingDate": "2019-05-29",
          "qualifyingAmountExpenditure": 567.67
        },
        "building": {
          "name": "Victoria Building",
          "number": "23",
          "postcode": "TF3 5GH"
        }
      }
    ],
    "enhancedStructuredBuildingAllowance": [
      {
        "amount": 445.56,
        "firstYear": {
          "qualifyingDate": "2019-09-29",
          "qualifyingAmountExpenditure": 565.56
        },
        "building": {
          "name": "Trinity House",
          "number": "20",
          "postcode": "TF4 7HJ"
        }
      }
    ],
    "zeroEmissionsCarAllowance": 678.78
  },
  "nonFinancials": {
    "businessDetailsChangedRecently": true,
    "class4NicsExemptionReason": "non-resident"
  },
  "links": [
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/annual/2019-20",
      "rel": "create-and-amend-self-employment-annual-submission",
      "method": "PUT"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/annual/2019-20",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/annual/2019-20",
      "rel": "delete-self-employment-annual-submission",
      "method": "DELETE"
    }
  ]
}
