=== hmrc/self-employment-business-api/resources/public/api/conf/1.0/schemas/retrieve_periodic_update_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Periodic Update Period",
  "description": "Get a single self-employment periodic update for a given identifier.",
  "type": "object",
  "properties": {
    "periodFromDate": {
      "description": "Start date for the period.",
      "type": "string",
      "example": "2017-01-25"
    },
    "periodToDate": {
      "description": "End date for the period.",
      "type": "string",
      "example": "2017-01-25"
    },
    "incomes": {
      "type": "object",
      "description": "Incomes.",
      "properties": {
        "turnover": {
          "type": "object",
          "description": "The takings, fees, sales or money earned by your business.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Income associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "10000.89"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "other": {
          "type": "object",
          "description": "Any other business income not included in turnover.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Other income associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "10000.89"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        }
      },
      "additionalProperties": false
    },
    "consolidatedExpenses": {
      "type": "object",
      "properties": {
        "consolidatedExpenses": {
          "type": "number",
          "description": "Sum of all expenses for the specified period. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "example": "1000.45"
        }
      },
      "additionalProperties": false,
      "required": ["consolidatedExpenses"]
    },
    "expenses": {
      "type": "object",
      "description": "Expenses.",
      "properties": {
        "costOfGoodsBought": {
          "type": "object",
          "description": "Cost of goods bought for resale or goods used.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "cisPaymentsTo": {
          "type": "object",
          "description": "Construction industry â€“ payments to subcontractors.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "staffCosts": {
          "type": "object",
          "description": "Wages, salaries and other staff costs.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "travelCosts": {
          "type": "object",
          "description": "Car, van and travel expenses.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "premisesRunningCosts": {
          "type": "object",
          "description": "Rent, rates, power and insurance costs.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "maintenanceCosts": {
          "type": "object",
          "description": "Repairs and renewals of property and equipment.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "adminCosts": {
          "type": "object",
          "description": "Phone, fax, stationery and other office costs.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "advertisingCosts": {
          "type": "object",
          "description": "Advertising Costs.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "businessEntertainmentCosts": {
          "type": "object",
          "description": "Business entertainment costs.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "interestOnLoans": {
          "type": "object",
          "description": "Interest on bank and other loans.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "financialCharges": {
          "type": "object",
          "description": "Bank, credit card and other financial charges.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "badDebt": {
          "type": "object",
          "description": "Irrecoverable debts written off.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "professionalFees": {
          "type": "object",
          "description": "Accountancy, legal and other professional fees.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "depreciation": {
          "type": "object",
          "description": "Depreciation and loss/profit on sales of assets.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        },
        "other": {
          "type": "object",
          "description": "Other business expenses.",
          "properties": {
            "amount": {
              "type": "number",
              "description": "Expenses associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            },
            "disallowableAmount": {
              "type": "number",
              "description": "Any expense or partial expense that cannot be claimed for tax purposes. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "1000.45"
            }
          },
          "additionalProperties": false,
          "required": ["amount"]
        }
      },
      "additionalProperties": false
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource.",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint.",
            "type": "string",
            "example": "/individuals/business/self-employment/{nino}/{businessId}/period/{periodId}"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource.",
            "type": "string",
            "enum": [
              "self",
              "amend-periodic-update"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint.",
            "type": "string",
            "enum": [
              "GET",
              "PUT"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "periodFromDate",
    "periodToDate"
  ]
}

=== hmrc/self-employment-business-api/resources/public/api/conf/1.0/examples/retrieve_periodic_update_consolidated_response.json
{
  "periodFromDate": "2019-04-29",
  "periodToDate": "2019-10-25",
  "incomes": {
    "turnover": {
      "amount": 172.89
    },
    "other": {
      "amount": 634.14
    }
  },
  "consolidatedExpenses": {
    "consolidatedExpenses": 647.89
  },
  "links": [
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period/2019-06-12_2020-06-12",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period/2019-06-12_2020-06-12",
      "rel": "amend-periodic-update",
      "method": "PUT"
    }
  ]
}

=== hmrc/self-employment-business-api/resources/public/api/conf/1.0/examples/retrieve_periodic_update_non_consolidated_response.json
{
  "periodFromDate": "2019-04-29",
  "periodToDate": "2019-10-25",
  "incomes": {
    "turnover": {
      "amount": 172.89
    },
    "other": {
      "amount": 634.14
    }
  },
  "expenses": {
    "costOfGoodsBought": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "cisPaymentsTo": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "staffCosts": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "travelCosts": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "premisesRunningCosts": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "maintenanceCosts": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "adminCosts": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "advertisingCosts": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "businessEntertainmentCosts": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "interestOnLoans": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "financialCharges": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "badDebt": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "professionalFees": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "depreciation": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    },
    "other": {
      "amount": 627.90,
      "disallowableAmount": 657.02
    }
  },
  "links": [
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period/2019-06-12_2020-06-12",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/business/self-employment/TC663795B/XAIS12345678910/period/2019-06-12_2020-06-12",
      "rel": "amend-periodic-update",
      "method": "PUT"
    }
  ]
}
