=== hmrc/self-employment-business-api/resources/public/api/conf/4.0/schemas/createAmendCumulativePeriodSummary/request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "TY 2025-26 and after",
  "description": "Create and Amend a Self-Employment Cumulative Period Summary",
  "type": "object",
  "properties": {
    "periodDates": {
      "type": "object",
      "description": "Object containing the details about self-employment period dates.",
      "properties": {
        "periodStartDate": {
          "description": "The first day that the income, expenses and deduction summary covers. Must conform to the format: YYYY-MM-DD",
          "type": "string",
          "example": "2025-04-06"
        },
        "periodEndDate": {
          "description": "The last day that the income, expenses and deduction summary covers. Must conform to the format: YYYY-MM-DD",
          "type": "string",
          "example": "2025-07-05"
        }
      },
      "required": [
        "periodStartDate",
        "periodEndDate"
      ]
    },
    "periodIncome": {
      "type": "object",
      "description": "Object containing the details about self-employment income.",
      "properties": {
        "turnover": {
          "description": "The takings, fees, sales or money earned by your business. Income associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.00"
        },
        "other": {
          "description": "Any other business income not included in turnover. Income associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.00"
        },
        "taxTakenOffTradingIncome": {
          "description": "Other tax taken off trading income apart from CIS deductions. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.00"
        }
      }
    },
    "periodExpenses": {
      "type": "object",
      "description": "Object containing the details about self-employment  expenses.",
      "properties": {
        "consolidatedExpenses": {
          "description": "The sum of all allowable expenses for the specified period. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.00"
        },
        "costOfGoods": {
          "description": "Cost of goods bought for resale or goods used. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.00"
        },
        "paymentsToSubcontractors": {
          "description": "Payments to construction Industry subcontractors. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.00"
        },
        "wagesAndStaffCosts": {
          "description": "Wages, salaries and other staff costs. Expenses associated with the running of the business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.00"
        },
        "carVanTravelExpneses": {
          "description": "Car, van and travel expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "premisesRunningCosts": {
          "description": "Rent, rates, power and insurance costs. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "maintenanceCosts": {
          "description": "Repairs and renewals of property and equipment. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "adminCosts": {
          "description": "Phone, fax, stationery and other office costs. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "businessEntertainmentCosts": {
          "description": "Business entertainment costs. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "advertisingCosts": {
          "description": "Advertising costs. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "interestOnBankOtherLoans": {
          "description": "Interest on bank and other loans. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "financeCharges": {
          "description": "Bank, credit card and other financial charges. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "irrecoverableDebts": {
          "description": "Irrecoverable debts written off. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "professionsalFees": {
          "description": "Accountancy, legal and other professional fees. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "depreciation": {
          "description": "Depreciation and loss/profit on sales of assets. Expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "otherExpenses": {
          "description": "Other business expenses associated with the running of the business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        }
      }
    },
    "periodDisallowableExpenses": {
      "type": "object",
      "description": "Object containing the details about self-employment disallowable expenses,  that cannot be claimed for tax purposes.",
      "properties": {
        "costOfGoodsDisallowable": {
          "description": "Cost of goods bought for resale or goods used. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "paymentsToSubcontractorsDisallowable": {
          "description": "Payments to subcontractors - Construction Industry Scheme (CIS). Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "wagesAndStaffCostsDisallowable": {
          "description": "Wages, salaries and other staff costs. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "carVanTravelExpensesDisallowable": {
          "description": "Car, van and travel expenses. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "premisesRunningCostsDisallowable": {
          "description": "Rent, rates, power and insurance costs. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "maintenanceCostsDisallowable" : {
          "description": "Repairs and renewals of property and equipment. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "adminCostsDisallowable": {
          "description": "Phone, fax, stationery and other office costs. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between-99999999999.99and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "businessEntertainmentCostsDisallowable": {
          "description": "Business entertainment costs. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "advertisingCostsDisallowable" : {
          "description": "Advertising costs. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between-99999999999.99and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "interestOnBankOtherLoansDisallowable": {
          "description": "Interest on bank and other loans. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "financeChargesDisallowable": {
          "description": "Bank, credit card and other financial charges. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "irrecoverableDebtsDisallowable": {
          "description": "Irrecoverable debts written off. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "professionalFeesDisallowable": {
          "description": "Legal and other professional fees. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "depreciationDisallowable": {
          "description": "Depreciation and loss/profit on sales of assets. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        },
        "otherExpensesDisallowable": {
          "description": "Other business expenses. Any expense or partial expense that cannot be claimed for tax purposes. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "10000.89"
        }
      }
    }
  }
}

=== hmrc/self-employment-business-api/resources/public/api/conf/4.0/examples/retrieveCumulativePeriodSummary/def1/non_consolidated_response.json
{
  "periodDates": {
    "periodStartDate": "2025-10-06",
    "periodEndDate": "2026-01-05"
  },
  "periodIncome": {
    "turnover": 200.00,
    "other": 200.00,
    "taxTakenOffTradingIncome": 1000.99
  },
  "periodExpenses": {
    "costOfGoods": 200.00,
    "paymentsToSubcontractors": 200.00,
    "wagesAndStaffCosts": 200.00,
    "carVanTravelExpenses": 200.00,
    "premisesRunningCosts": 200.00,
    "maintenanceCosts": 200.00,
    "adminCosts": 200.00,
    "businessEntertainmentCosts": 200.00,
    "advertisingCosts": 200.00,
    "interestOnBankOtherLoans": 200.00,
    "financeCharges": 200.00,
    "irrecoverableDebts": 200.00,
    "professionalFees": 200.00,
    "depreciation": 200.00,
    "otherExpenses": 200.00
  },
  "periodDisallowableExpenses": {
    "costOfGoodsDisallowable": 200.00,
    "paymentsToSubcontractorsDisallowable": 200.00,
    "wagesAndStaffCostsDisallowable": 200.00,
    "carVanTravelExpensesDisallowable": 200.00,
    "premisesRunningCostsDisallowable": 200.00,
    "maintenanceCostsDisallowable": 200.00,
    "adminCostsDisallowable": 200.00,
    "businessEntertainmentCostsDisallowable": 200.00,
    "advertisingCostsDisallowable": 200.00,
    "interestOnBankOtherLoansDisallowable": 200.00,
    "financeChargesDisallowable": 200.00,
    "irrecoverableDebtsDisallowable": 200.00,
    "professionalFeesDisallowable": 200.00,
    "depreciationDisallowable": 200.00,
    "otherExpensesDisallowable": 200.00
  }
}
